platform :ios, '14.0'

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
         end
    end
  end
end

target 'VerseeScan' do
  use_frameworks!
  inhibit_all_warnings!
  pod 'Progress'
  pod 'GDPerformanceView-Swift', '~> 2.1.1'
  pod 'Firebase/Auth'
end
